version: '3'
services:
  ubuntu-jdk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-jdk-container
    # 호스트와 공유할 디렉토리 마운트
    # volumes:
    #   - ./app:/app
    # 기타 설정들 추가
    command: tail -f /dev/null  # 컨테이너가 종료되지 않도록 대기

  spring-app:
    image: spring-boot-tetimage:1
    container_name: spring-app-container
    # 호스트와 공유할 디렉토리 마운트
    # volumes:
    #   - ./app:/app
    ports:
      - "8080:8080"
    # 기타 설정들 추가
    depends_on:
      - ubuntu-jdk
